package com.example.api

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONArray
import java.io.IOException
import java.net.URLEncoder
import java.util.concurrent.TimeUnit

object GoogleTranslateHelper {
    private val client = OkHttpClient.Builder()
        .connectTimeout(10, TimeUnit.SECONDS)
        .readTimeout(10, TimeUnit.SECONDS)
        .build()

    /**
     * Translates text to Thai using Google Translate web API (free, fast, no API key required).
     */
    suspend fun translateToThai(text: String, sourceLang: String = "auto"): String = withContext(Dispatchers.IO) {
        if (text.isBlank()) return@withContext ""
        val encoded = URLEncoder.encode(text, "UTF-8")
        val url = "https://translate.googleapis.com/translate_a/single?client=gtx&sl=$sourceLang&tl=th&dt=t&q=$encoded"
        val request = Request.Builder()
            .url(url)
            .header("User-Agent", "Mozilla/5.0 (Linux; Android 10; Mobile)")
            .build()

        client.newCall(request).execute().use { response ->
            if (!response.isSuccessful) {
                throw IOException("Google Translate error: HTTP ${response.code}")
            }
            val body = response.body?.string() ?: throw IOException("Empty response from Google Translate")
            parseGoogleTranslateJson(body)
        }
    }

    private fun parseGoogleTranslateJson(jsonStr: String): String {
        val jsonArray = JSONArray(jsonStr)
        val sentencesArray = jsonArray.getJSONArray(0)
        val sb = StringBuilder()
        for (i in 0 until sentencesArray.length()) {
            val sentence = sentencesArray.getJSONArray(i)
            sb.append(sentence.getString(0))
        }
        return sb.toString()
    }

    /**
     * Replaces standard pronouns generated by Google Translate (ผม, คุณ, ข้าพเจ้า, ฯลฯ)
     * with the user's custom pronoun pairs (e.g. ฉัน/เธอ, ข้า/เอ็ง, กู/มึง).
     */
    fun applyCustomPronouns(translatedText: String, pronounConfig: String): String {
        if (pronounConfig.isBlank() || translatedText.isBlank()) return translatedText

        val parts = pronounConfig.split("/", ",", " ")
            .map { it.trim() }
            .filter { it.isNotEmpty() }

        if (parts.size < 2) return translatedText

        val p1 = parts[0] // 1st person (e.g., ข้า, กู, ฉัน, พี่)
        val p2 = parts[1] // 2nd person (e.g., เอ็ง, มึง, เธอ, นาย, น้อง)

        var result = translatedText

        // 1st person substitution
        if (p1 != "ผม") {
            result = result.replace("ข้าพเจ้า", p1)
            result = result.replace("กระผม", p1)
            result = result.replace("ผม", p1)
        }
        if (p1 != "ฉัน") {
            result = result.replace("ฉัน", p1)
        }

        // 2nd person substitution
        if (p2 != "คุณ") {
            result = result.replace("คุณ", p2)
        }
        if (p2 != "ท่าน" && p2 != "นายท่าน") {
            result = result.replace("ท่าน", p2)
        }
        if (p2 != "เธอ" && p2 != "นาย") {
            result = result.replace("เธอ", p2)
        }

        return result
    }
}
